name: solarscheme

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.11
  - pip=23.2.1
  - pytest
  - pandas=2.1.1
  - numpy=1.26.0
  - uvicorn-standard=0.23.2
  - pip:
    - -r requirements.txt

