service: fastapi-solar-scheme

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: us-east-1

package:
  individually: true
  patterns:
    - "!requirements.txt"
    - "!package.json"

layers:
  fastApi:
    path: fastApi
    name: fastApi
    description: lambda layer for fastapi related dependencies
    compatibleRuntimes:
      - python3.11
    retain: false

functions:
  users:
    handler: app.main.handler
    layers:
      - !Ref FastApiLambdaLayer 
    url: true  